frase = 'Curso em video Python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1:15])
print(frase[1:15:2])
print(frase[:])
print(frase.upper())
print(frase.count('o'))
print(frase.upper().count('O'))
print(frase.lower().find("video"))
print(len(frase))
print(len(frase.strip()))
print(frase.replace('Python', 'Android'))
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.find('curso'))
print(frase.split())
dividido = frase.split()
print(dividido [2] [4])
print(''.join(dividido))
